reapplied nfs_utils, fixed cluster.yml, updated metal Makefile

diff --git a/bootstrap/Makefile b/bootstrap/Makefile
--- a/bootstrap/Makefile
+++ b/bootstrap/Makefile
@@ -1,27 +1,26 @@
 .POSIX:
 
-default: namespace argocd root
+default: namespace check-namespaces argocd root
 
 namespace:
 	kubectl create namespace argocd --dry-run=client --output=yaml \
 		| kubectl apply -f -
-	@echo "Namespace argocd created."
+	sleep 60
+
+.PHONY: check-namespaces
+check-namespaces:
+	@echo "Checking if namespaces and CRDs are available..."
+	@kubectl get namespace argocd &> /dev/null || (echo "Namespace argocd not found."; exit 1)
+	@kubectl get crd applications.argoproj.io &> /dev/null || (echo "CRD applications.argoproj.io not found."; exit 1)
+	@kubectl get crd applicationsets.argoproj.io &> /dev/null || (echo "CRD applicationsets.argoproj.io not found."; exit 1)
+	@echo "Namespaces and CRDs are available."
 
 .PHONY: argocd
-argocd: wait_for_crd
-	cd argocd && ./apply.sh
+argocd:
+	@echo "Proceeding with argocd..."
+	@cd argocd && ./apply.sh
 
 .PHONY: root
 root:
-	cd root && ./apply.sh
-
-.PHONY: wait_for_crd
-wait_for_crd:
-	@echo "Waiting for CRDs to become available..."
-	@until kubectl get crd applications.argoproj.io applicationsets.argoproj.io &> /dev/null; do \
-		echo "CRDs not found. Retrying in 5 seconds..."; \
-		sleep 5; \
-	done
-	@echo "CRDs are available."
-	sleep 5
-
+	@echo "Proceeding with root..."
+	@cd root && ./apply.sh
